spring.application.name=biosense-ai-backend

server.port=8080

spring.jpa.open-in-view=false

spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration